const now = "2026-08-20T13:00:00.000Z";
const provenance = [{ source: "official_provider", providerObjectId: "fixture-1", providerUpdatedAt: now, observedAt: now, contentHash: "fixture-hash", freshness: "fresh" }];
const base = { schemaVersion: "1.0", viewId: "review-fixture", generatedAt: now, timezone: "America/New_York", provenance, capabilities: { job_read: "verified_read_only", proposal_submission: "verified_read_write" }, warnings: [] };
const job = { entityType: "job", provider: "official_marketplace", providerObjectId: "job-fixture", observedAt: now, source: "official_provider", title: "Revenue Operations & HubSpot Implementation", description: "Audit the current HubSpot system, redesign lifecycle and deal stages, implement clean automation, document the revenue process, and train the sales team with measurable acceptance criteria.", skills: ["HubSpot", "RevOps", "CRM"], status: "open", contractType: "hourly", currency: "USD", hourlyMinMinor: 8000, hourlyMaxMinor: 12000, connectsCost: 12, attachments: [] };
const score = { version: "opportunity-v1", score: 87, classification: "strong", factors: [], riskPenalty: 3, hardGateReasons: [], matchedProofClaimIds: ["proof-1", "proof-2"], confidence: "high" };

export const REVIEW_FIXTURES: Record<string, Record<string, unknown>> = {
  capabilities: { ...base, surface: "capabilities", summary: "Revenue Copilot is ready. Review capability badges before provider-facing work.", data: { status: { accountConnected: true, providerLastCheckedAt: now, capabilities: { job_read: "verified_read_only", proposal_submission: "verified_read_write", profile_update: "unknown", service_update: "manual_handoff" }, historyCounts: { job: 18, proposal: 9, conversation: 4, message: 21, contract: 2, milestone: 3, profile: 1, service: 2, connects_observation: 1, revenue_event: 6 }, draftCount: 3, proofCount: 8, dataRetention: "until_user_deletes" } } },
  revenue_pulse: { ...base, surface: "revenue_pulse", summary: "Three highest-value next moves identified.", data: { actions: [{ id: "opportunity:job-fixture", kind: "opportunity", title: "Review HubSpot implementation role", reason: "Strong fit at 87/100 with two approved proof claims and a verified client.", estimatedUpside: "High-value proposal opportunity", priority: 1, targetId: "job-fixture" }, { id: "inbox:conversation-1", kind: "inbox", title: "Reply to an active prospect", reason: "One unread message asks for availability and next steps.", estimatedUpside: "Protect pipeline momentum", priority: 2, targetId: "conversation-1" }, { id: "milestone:milestone-1", kind: "workroom", title: "Check CRM discovery milestone", reason: "The next official deadline is tomorrow at 3:00 PM.", estimatedUpside: "Protect delivery and payment", priority: 3, targetId: "milestone-1" }], officialRevenueMinor: 420000, officialRevenueCurrency: "USD", connectsBalance: 228 } },
  opportunity_review: { ...base, surface: "opportunity_review", summary: "Revenue Operations & HubSpot Implementation: 87/100 strong fit.", data: { opportunities: [{ job, score }], totalAvailable: 1 } },
  proposal_studio: { ...base, surface: "proposal_studio", summary: "Draft saved and ready for provider review. Nothing has been submitted.", data: { draft: { id: "rc-proposal-fixture", jobProviderObjectId: "job-fixture", version: 3, status: "ready_for_review", opening: "Your HubSpot project needs a revenue-process decision before another layer of automation is added.", proof: "I led CRM implementations that connected lifecycle stages to measurable revenue operations and documented the resulting handoffs.", approach: "I would validate the current funnel and data model first, lock acceptance criteria, then implement the smallest high-leverage workflow before expanding the rollout.", questions: ["Which lifecycle transition is currently causing the most lost revenue?", "Who owns final acceptance for sales and operations?"], closing: "If this direction matches the outcome you need, I can begin with a focused discovery and architecture pass.", proofClaimIds: ["proof-1"], unsupportedClaims: [], screeningAnswers: [], createdAt: now, updatedAt: now }, score, readyForProviderReview: true, claimCoverage: [], nothingSubmitted: true, replayed: false } },
  inbox_triage: { ...base, surface: "inbox_triage", summary: "Two conversations triaged. Nothing has been sent.", data: { conversations: [{ conversation: { entityType: "conversation", provider: "official_marketplace", providerObjectId: "conversation-1", observedAt: now, source: "official_provider", participantLabel: "SaaS operations client", unreadCount: 1 }, messages: [{ entityType: "message", provider: "official_marketplace", providerObjectId: "message-1", observedAt: now, source: "official_provider", conversationProviderObjectId: "conversation-1", senderLabel: "Client", body: "Can you start next week, and what would you need from our team before kickoff?", sentAt: now, direction: "inbound", attachments: [] }], priority: "today", reason: "There is an unread official message asking for availability.", suggestedReply: "Thanks for the update. I can reserve time next week; before kickoff I would need your current lifecycle definitions, pipeline stages, and one owner for final acceptance." }], nothingSent: true } },
  workroom: { ...base, surface: "workroom", summary: "One workroom reviewed. Nothing has been submitted.", data: { workrooms: [{ contract: { entityType: "contract", provider: "official_marketplace", providerObjectId: "contract-1", observedAt: now, source: "official_provider", title: "HubSpot revenue process redesign", clientLabel: "Synthetic SaaS client", status: "active", contractType: "fixed", currency: "USD", amountMinor: 480000 }, milestones: [{ entityType: "milestone", provider: "official_marketplace", providerObjectId: "milestone-1", observedAt: now, source: "official_provider", contractProviderObjectId: "contract-1", title: "Discovery and architecture", status: "active", amountMinor: 120000, currency: "USD", dueAt: "2026-08-21T19:00:00.000Z", funded: true }], urgency: "due_soon", nextAction: "Review the discovery packet and prepare the official-provider milestone handoff if delivery is ready." }], nothingSubmitted: true } },
  market_presence: { ...base, surface: "market_presence", summary: "Two market-presence suggestions. Nothing has been changed.", data: { profiles: [], services: [], suggestions: [{ area: "profile", providerObjectId: "profile-1", title: "Make the profile title outcome-specific", rationale: "The current title is broad and hides the highest-value service.", currentValue: "CRM & Automation Consultant", suggestedValue: "Revenue Operations & CRM Architect | HubSpot + Salesforce", evidenceNeeded: [] }, { area: "service", providerObjectId: "service-1", title: "Lead with the diagnostic outcome", rationale: "The package currently describes tasks before the business result.", currentValue: "I will set up your CRM", suggestedValue: "Find and fix the CRM leaks costing your team revenue", evidenceNeeded: ["Approved portfolio example showing the diagnostic method"] }], nothingChanged: true } }
};
